### ISSUE TITLE
Ordinal indicator is incorrect for 21st/22nd/23rd and 31st - all display as "th"

### ISSUE THREAD

**Issue by nmcgann** [remi-grumeau/DatePicker#6]
Just requires some additional `case 21:` etc. in `drawCalendar`.

**Comment by nmcgann** [comment]
This is incorrect in toString too.

**Comment by remi-grumeau** [comment]
Very good point!
Have a quick fix patch ?

Remi

**Comment by nmcgann** [comment]
Yes, I will do a proper pull request in the next few days. I also have a fix for the "NaN" issue that shows up in the displayed date if an input field is manually entered and only partially completed (e.g. Only the year is entered, the picker is closed and then re-opened - days and months show as NaN. The demo can show it in the "single input at defined position" version where the input field is still accessible).

**Comment by remi-grumeau** [comment]
Cool !
Looking forward for your PR


Remi
